[package]
name = "pandora-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
emojis = "0.6.4"
miette = { version = "7.2.0", features = ["fancy"] }
strum = "0.26"
strum_macros = "0.26"
symbol = "0.1.9"
thiserror = "1.0.67"
unicode-xid = "0.2.6"
# llvm-sys = { package = "llvm-sys", version = "180", features = ["prefer-static"] }
inkwell = { version = "0.5.0", features = ["llvm18-0"] }
